# Generated by Django 3.1.4 on 2021-01-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicatie2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=25)),
                ('titlu', models.CharField(choices=[('programator', 'programator'), ('medic', 'medic'), ('Pilot de instalare în industrii chimice', 'Pilot de instalare în industrii chimice '), ('Operator ', 'Operator '), ('Pilot instalare industria', 'Pilot instalare industria'), ('Asistant', 'Asistant'), ('Agent', 'Agent')], max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('how_to_apply', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie2.companies')),
            ],
        ),
    ]
